CREATE USER NODEREDAPP1 IDENTIFIED BY "22";
GRANT CONNECT            TO NODEREDAPP1;
GRANT ALTER SESSION      TO NODEREDAPP1;
GRANT CUSTDOC_OPER TO NODEREDAPP1;

CREATE USER NODEREDAPP2 IDENTIFIED BY "22";
GRANT CONNECT            TO NODEREDAPP1;
GRANT ALTER SESSION      TO NODEREDAPP1;
GRANT CUSTDOC_OPER TO NODEREDAPP1;