GRANT SELECT, INSERT, UPDATE, DELETE  ON  CUSTDOC.CUST$DOCS$ATTACH TO CUSTDOC_OPER;
GRANT SELECT, INSERT, UPDATE, DELETE  ON  CUSTDOC.CUST$DOCS$URLS TO CUSTDOC_OPER;
GRANT SELECT, INSERT, UPDATE, DELETE  ON  CUSTDOC.CUST$DOCS        TO CUSTDOC_OPER;
GRANT SELECT                          ON  CUSTDOC.CUST$D$DOCTYPE   TO CUSTDOC_OPER;

GRANT SELECT, INSERT, UPDATE, DELETE  ON CUSTDOC.CUST$ARTIST  TO CUSTDOC_OPER;

