CREATE TABLE CUSTDOC.CUST$DOCS
( IDDOC      INTEGER NOT NULL,
  CUSTID     VARCHAR2(9),
  TYPEDOC    VARCHAR2(32),
  ISACRUAL   VARCHAR2(1),
  IUSRNM     VARCHAR2(30),
  IDT        DATE,
  MUSRNM     VARCHAR2(30),
  MDT        DATE,
  CONSTRAINT CUST$DOCS_PK         PRIMARY KEY (IDDOC),
  CONSTRAINT CUST$DOCS_ISACRUAL   CHECK( ISACRUAL IN ('Y', 'N')),
  CONSTRAINT CUST$DOCS_CUSTID   CHECK( CUSTID  IS NOT NULL),
  CONSTRAINT CUST$DOCS_TYPEDOC   CHECK( TYPEDOC  IS NOT NULL),
  CONSTRAINT CUST$DOCS_FK_IDDOC foreign key (TYPEDOC) references CUSTDOC.CUST$D$DOCTYPE ( TYPEDOC ),
  CONSTRAINT CUST$DOCS_FK_CUSTID foreign key (CUSTID) references CUSTDOC.CUST$CUST (CUSTID) ON DELETE CASCADE
) 
/

COMMENT ON TABLE CUSTDOC.CUST$DOCS IS 'Customer Documents';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.IDDOC   IS 'Document Identifier';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.CUSTID      IS 'Customer Identifier';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.TYPEDOC     IS 'Type of Document';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.ISACRUAL    IS 'Migration Flag (Y-Not mirated, N-Migrated)';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.IUSRNM      IS 'Who Inserted the record';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.IDT         IS 'Date and Time of Insertion';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.MUSRNM      IS 'Who Modified the record';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.MDT         IS 'Date and Time of Modification'; 




CREATE INDEX CUSTDOC.CUST$DOCS_IDX_TYPEDOC ON CUSTDOC.CUST$DOCS(TYPEDOC); 
