CREATE TABLE CUSTDOC.CUST$D$DOCTYPE
( TYPEDOC    VARCHAR2(32) NOT NULL,
  NAMETYPE   VARCHAR2(64),
  IUSRNM     VARCHAR2(30),
  IDT        DATE,
  MUSRNM     VARCHAR2(30),
  MDT        DATE,
  CONSTRAINT CUST$D$DOCTYPE_PK         PRIMARY KEY (TYPEDOC),
  CONSTRAINT CUST$D$DOCTYPE_NAMETYPE   CHECK( NAMETYPE  IS NOT NULL)
) 
/

COMMENT ON TABLE CUSTDOC.CUST$D$DOCTYPE IS 'Types Customer Documents';
COMMENT ON COLUMN CUSTDOC.CUST$D$DOCTYPE.TYPEDOC   IS 'TYPE DOCUMET';
COMMENT ON COLUMN CUSTDOC.CUST$D$DOCTYPE.IUSRNM       IS 'Who Inserted the record';
COMMENT ON COLUMN CUSTDOC.CUST$D$DOCTYPE.IDT          IS 'Date and Time of Insertion';
COMMENT ON COLUMN CUSTDOC.CUST$D$DOCTYPE.MUSRNM       IS 'Who Modified the record';
COMMENT ON COLUMN CUSTDOC.CUST$D$DOCTYPE.MDT          IS 'Date and Time of Modification'; 

