CREATE TABLE CUSTDOC.CUST$DOCS
( IDDOC      INTEGER NOT NULL,
  CUSTID     VARCHAR2(9),
  TYPEDOC    VARCHAR2(32),
  ISACRUAL   VARCHAR2(1),
  IUSRNM     VARCHAR2(30),
  IDT        DATE,
  MUSRNM     VARCHAR2(30),
  MDT        DATE,
  CONSTRAINT CUST$DOCS_PK         PRIMARY KEY (IDDOC),
  CONSTRAINT CUST$DOCS_ISACRUAL   CHECK( ISACRUAL IN ('Y', 'N')),
  CONSTRAINT CUST$DOCS_CUSTID   CHECK( CUSTID  IS NOT NULL),
  CONSTRAINT CUST$DOCS_TYPEDOC   CHECK( TYPEDOC  IS NOT NULL),
  CONSTRAINT CUST$DOCS_FK_IDDOC foreign key (TYPEDOC) references CUSTDOC.CUST$D$DOCTYPE ( TYPEDOC )
) 
/

COMMENT ON TABLE CUSTDOC.CUST$DOCS IS 'Customer Documents';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS.IDDOC   IS 'Document IDentifier';



CREATE INDEX CUSTDOC.CUST$DOCS_IDX_TYPEDOC ON CUSTDOC.CUST$DOCS(TYPEDOC); 