CREATE TABLE CUSTDOC.CUST$DOCS$ATTACH
( IDFL         INTEGER NOT NULL,
  IDDOC        INTEGER ,
  FILE_NAME    VARCHAR2(120),
  FILE_CONTENT BLOB,
  FILE_DESC    VARCHAR2(120),
  IUSRNM       VARCHAR2(30),
  IDT          DATE,
  MUSRNM       VARCHAR2(30),
  MDT          DATE,
  CONSTRAINT CUST$DOCS$ATTACH_PK  PRIMARY KEY (IDFL),
  CONSTRAINT CUST$DOCS$ATTACH_FILE_NAME  CHECK( FILE_NAME IS NOT NULL),
  CONSTRAINT CUST$DOCS$ATTACH_IDDOC  CHECK( IDDOC IS NOT NULL),
  CONSTRAINT CUST$DOCS$ATTACH_FK_IDDOC foreign key (IDDOC) references CUSTDOC.CUST$DOCS ( IDDOC) ON DELETE CASCADE
) 
/

COMMENT ON TABLE CUSTDOC.CUST$DOCS$ATTACH IS 'Customer Documents: Attached files';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.IDFL         IS 'File IDentifier';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.IDDOC        IS 'Document IDentifier';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.FILE_NAME    IS 'Document File name ';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.FILE_CONTENT IS 'Document binary content'; 
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.FILE_DESC    IS 'Document description while uploading';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.IUSRNM       IS 'Who Inserted the record';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.IDT          IS 'Date and Time of Insertion';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.MUSRNM       IS 'Who Modified the record';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.MDT          IS 'Date and Time of Modification'; 




CREATE INDEX CUSTDOC.CUST$DOCS$ATTACH_IDX_IDDOC ON CUSTDOC.CUST$DOCS$ATTACH(IDDOC) ;
