CREATE TABLE CUSTDOC.CUST$DOCS$ATTACH
( IDFL         INTEGER NOT NULL,
  IDDOC        INTEGER ,
  FILE_NAME    VARCHAR2(120),
  FILE_CONTENT BLOB,
  FILE_DESC    VARCHAR2(120),
  IUSRNM       VARCHAR2(30),
  IDT          DATE,
  MUSRNM       VARCHAR2(30),
  MDT          DATE,
  CONSTRAINT CUST$DOCS$ATTACH_PK  PRIMARY KEY (IDFL),
  CONSTRAINT CUST$DOCS$ATTACH_FILE_NAME  CHECK( FILE_NAME IS NOT NULL),
  CONSTRAINT CUST$DOCS$ATTACH_IDDOC  CHECK( IDDOC IS NOT NULL),
  CONSTRAINT CUST$DOCS$ATTACH_FK_IDDOC foreign key (IDDOC) references CUSTDOC.CUST$DOCS ( IDDOC)
) 
/

COMMENT ON TABLE CUSTDOC.CUST$DOCS$ATTACH IS 'Customer Documents Attached files';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.IDFL    IS 'File IDentifier';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$ATTACH.IDDOC   IS 'Document IDentifier';




CREATE INDEX CUSTDOC.CUST$DOCS$ATTACH_IDX_IDDOC ON CUSTDOC.CUST$DOCS$ATTACH(IDDOC) ;
