CREATE TABLE CUSTDOC.CUST$DOCS$URLS
( IDFL         INTEGER NOT NULL,
  IDDOC        INTEGER ,
  FILE_NAME    VARCHAR2(120),
  CONTAINER_NAME  VARCHAR2(120),
  CONTENT_TYPE VARCHAR2(80),
  FILE_SIZE    INTEGER,
  FILE_URL     VARCHAR2(240),
  FILE_DESC    VARCHAR2(120),
  IUSRNM       VARCHAR2(30),
  IDT          DATE,
  MUSRNM       VARCHAR2(30),
  MDT          DATE,
  CONSTRAINT CUST$DOCS$URLS_PK  PRIMARY KEY (IDFL),
  CONSTRAINT CUST$DOCS$URLS_FILE_NAME  CHECK( FILE_NAME IS NOT NULL),
  CONSTRAINT CUST$DOCS$URLS_IDDOC  CHECK( IDDOC IS NOT NULL),
  CONSTRAINT CUST$DOCS$URLS_FK_IDDOC foreign key (IDDOC) references CUSTDOC.CUST$DOCS ( IDDOC) ON DELETE CASCADE
) 
/

COMMENT ON TABLE CUSTDOC.CUST$DOCS$URLS IS 'Migrated On Blob Storage Customer Documents ';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.IDFL            IS 'File IDentifier';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.IDDOC           IS 'Document IDentifier';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.FILE_NAME       IS 'Document file name';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.CONTAINER_NAME  IS 'Blob Storage Container Name';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.CONTENT_TYPE    IS 'Document MIME Type';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.FILE_SIZE       IS 'Size of document ';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.FILE_URL        IS 'File Blob Storage URL ';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.FILE_DESC       IS 'File Description';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.IUSRNM          IS 'Who Inserted the record';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.IDT             IS 'Date and Time of Insertion';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.MUSRNM          IS 'Who Modified the record';
COMMENT ON COLUMN CUSTDOC.CUST$DOCS$URLS.MDT             IS 'Date and Time of Modification'; 




CREATE INDEX CUSTDOC.CUST$DOCS$URLS_IDX_IDDOC ON CUSTDOC.CUST$DOCS$URLS(IDDOC) ;
