CREATE TABLE CUSTDOC.CUST$CUST
(
  CUSTID     VARCHAR2(9),
  CUSTTYPE   VARCHAR2(2),
  CUSTNAME   VARCHAR2(180),
  IUSRNM     VARCHAR2(30),
  IDT        DATE,
  MUSRNM     VARCHAR2(30),
  MDT        DATE,
  CONSTRAINT CUST$CUST_PK         PRIMARY KEY (CUSTID),
  CONSTRAINT CUST$CUST_T   CHECK( CUSTTYPE IN ('CI', 'LE')),
  CONSTRAINT CUST$CUST_N   CHECK( CUSTNAME  IS NOT NULL)
)
  
/

COMMENT ON TABLE CUSTDOC.CUST$CUST IS 'Customer Records';


COMMENT ON COLUMN CUSTDOC.CUST$CUST.CUSTID      IS 'CUSTOMER IDentifier';
COMMENT ON COLUMN CUSTDOC.CUST$CUST.CUSTTYPE    IS 'CUSTOMER TYPE ( CI - Individuals, LE -LEgal Entities)'; 
COMMENT ON COLUMN CUSTDOC.CUST$CUST.CUSTNAME    IS 'Customer name';
COMMENT ON COLUMN CUSTDOC.CUST$CUST.IUSRNM      IS 'Who Inserted the record';
COMMENT ON COLUMN CUSTDOC.CUST$CUST.IDT         IS 'Date and Time of Insertion';
COMMENT ON COLUMN CUSTDOC.CUST$CUST.MUSRNM      IS 'Who Modified the record';
COMMENT ON COLUMN CUSTDOC.CUST$CUST.MDT         IS 'Date and Time of Modification'; 



