
PROMPT ===========================================

PROMPT CUSTDOC.CUST$D$DOCTYPE
@@CUST_DOCS_DOCTYPE

PROMPT CREATE CUST$DOCS
@@CUST_DOCS.sql

PROMPT CREATE CUST$DOCS$ATTACH
@@CUST_DOCS_ATTACH

PROMPT CREATE CUSTDOC.CUST$ARTIST
@@ARTIST.sql



