insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('NAT_ID', 'National Identity Document')
/

insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('FOR_PASS', 'International Passport')
/


insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('BIRTH_CERT', 'Birth Certificate	')
/

insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('TAX_ID', 'Tax Identification Number')
/


insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('DRV_LIC', '	Drivers License')
/

insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('COI', 'Certificate of Incorporation')
/


insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('REG_EXT', 'Company Register Extract')
/

insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('PoA', 'Power of Attorney')
/

insert into CUSTDOC.CUST$D$DOCTYPE( TYPEDOC, NAMETYPE)
   values('AoA', 'Articles of Association ( Charter )')
/

COMMIT;



